# Generated by Django 4.1.4 on 2023-02-11 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Elev',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume', models.TextField()),
                ('prenume', models.TextField()),
                ('an', models.IntegerField()),
                ('telefon', models.IntegerField()),
            ],
        ),
    ]
