# Generated by Django 4.1.4 on 2023-02-26 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curs_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='elev',
            options={'verbose_name_plural': 'Elevi'},
        ),
        migrations.AddField(
            model_name='elev',
            name='cnp_student',
            field=models.IntegerField(default=123),
            preserve_default=False,
        ),
    ]
