# Generated by Django 4.1.4 on 2023-02-26 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curs_manager', '0002_alter_elev_options_elev_cnp_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elev',
            name='cnp_student',
            field=models.IntegerField(blank=True, max_length=13, null=True, unique=True),
        ),
    ]
