# Generated by Django 4.1.4 on 2023-02-26 13:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curs_manager', '0004_alter_elev_cnp_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elev',
            name='cnp_student',
            field=models.CharField(blank=True, max_length=13, null=True, unique=True, validators=[django.core.validators.MinLengthValidator(13)]),
        ),
    ]
