# Generated by Django 4.1.4 on 2023-02-26 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curs_manager', '0005_alter_elev_cnp_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elev',
            name='an',
            field=models.IntegerField(db_index=True, default=1),
        ),
        migrations.AlterField(
            model_name='elev',
            name='telefon',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
