# Generated by Django 4.1.4 on 2023-02-27 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('curs_manager', '0006_alter_elev_an_alter_elev_telefon'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adresa',
            fields=[
                ('elev_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='curs_manager.elev')),
                ('strada', models.CharField(max_length=33)),
                ('judet', models.CharField(max_length=15)),
                ('cod_postal', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Adrese',
            },
            bases=('curs_manager.elev',),
        ),
    ]
