# Generated by Django 4.1.4 on 2023-02-28 05:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('curs_manager', '0008_adresa_oras'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdresNoua',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strada', models.CharField(max_length=33)),
                ('oras', models.CharField(max_length=30)),
                ('judet', models.CharField(max_length=15)),
                ('cod_postal', models.IntegerField()),
                ('elev', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curs_manager.elev')),
            ],
            options={
                'verbose_name_plural': 'Adrese',
            },
        ),
    ]
