# Generated by Django 4.1.4 on 2023-02-28 05:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('curs_manager', '0009_adresnoua'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElevProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('varsta', models.IntegerField()),
                ('elev', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='curs_manager.elev')),
            ],
        ),
    ]
